#####################################################################################
### DeathLocation - Shows the location where you died                             ###
###                                                                               ###
### You can find the source code at: https://github.com/Xitee1/DeathLocation      ###
#####################################################################################

##############
### Config ###
##############
# In what places the message should appear
types:
  chat-message: true
  actionbar: true
  title: false

actionbar:
  # Duration show duration (in seconds)
  timeout: 15

# Send the message to all players on the server?
# Only recommended if you want that other players are easily able to steal someone's stuff or find their base!
allPlayers: false

message:
  # The location will be appended to the existing death message (only chat). Warning: Every player will see the location, like the "allPlayers" option!
  append: false

  # Placeholders: %player, %displayname, %x, %y, %z
  message: '&4You died at &b%x %y %z'
  messageOther: '&4%player died at &b%x %y %z'


######################
### Plugin Updater ###
######################
# Notifies all admins about a new version
update:
  notification: true
  
#############################################
#### The debug can help you find problems ###
#############################################
debug: false